name: wifi_v1
description: "Spreadsheet visualizer with theme controls and interactive charts."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  file_picker: ^8.0.0
  excel: ^2.1.0
  csv: ^5.0.2
  fl_chart: ^0.68.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
